version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
  books:
    image: golang
    container_name: books
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://docker:docker@postgres:5432/books
    volumes:
      - ./books-poc:/books-poc
    command: /books-poc
    restart: always
